---
name: 'Gitlab CI Pipeline Trigger'
description: 'Pushes PR to GitLab repo to trigger GLCI, canceling all other GLCI pipelines for same branch'
author: 'SIMP Team'
inputs:
  git_branch:
    description: Branch name to use when pushing to gitlab/GLCI
    required: true
  git_hashref:
    description: Hashref of git commit to push to GLCI
    required: true
  gitlab_api_private_token:
    description: GitLab API private token (should have `api` scope)
    required: true
  gitlab_group:
    description: Gitlab Group to push to
    required: true
    default: ${{ github.event.organization.login }}
  gitlab_server_url:
    description: Specify a GitLab server other than gitlab.com
    required: true
    default: 'https://gitlab.com'
  gitlab_api_url:
    description: Specify a GitLab API other than gitlab.com
    required: true
    default: 'https://gitlab.com/api/v4'
  github_repository:
    description: TODO
    required: true
    default: ${{ github.repository }}
  github_repository_owner:
    description: TODO
    required: true
    default: ${{ github.repository_owner }}
branding:
  icon: gitlab
  color: green

runs:
  using: "composite"

  steps:
    - name: Trigger CI
      shell: bash
      env:
        GIT_HASHREF: ${{ inputs.git_hashref }}
        GIT_BRANCH: ${{ inputs.git_branch }}
        GITLAB_GROUP: ${{ inputs.gitlab_group }}
        GITHUB_REPOSITORY: ${{ inputs.github_repository }}
        GITHUB_REPOSITORY_OWNER: ${{ inputs.github_repository_owner }}
        GITLAB_API_PRIVATE_TOKEN: ${{ inputs.gitlab_api_private_token }}
        GITLAB_SERVER_URL: ${{ inputs.gitlab_server_url }}
        GITLAB_API_URL: ${{ inputs.gitlab_api_url }}
      run: ${{ github.action_path }}/trigger_glci_pipeline.bash

